---
title: DAULOUDET BLANDINE
date: 15/09/2025
output: github_document
---

## Chargement des packages et des données

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
plastic_waste <- read_csv("data/plastic-waste.csv")
```

Commençons par filtrer les données pour retirer le point représenté par Trinité et Tobago (TTO) qui est un outlier.

```{r filter-data, message=FALSE}
plastic_waste <- plastic_waste %>%
  filter(plastic_waste_per_cap < 3.5)
```


## Exercices

### Exercise 1

```{r plastic-waste-continent}
ggplot(plastic_waste, aes(x= plastic_waste_per_cap, ))+ geom_histogram(binwidth =0.2) + facet_wrap(~continent)
```

### Exercise 2

```{r plastic-waste-density}
# insert code here
library(ggplot2)
ggplot(plastic_waste, aes(x=plastic_waste_per_cap, fill = continent, color=continent)) + geom_density(ajust=2, alpha=0.5)
```

Réponse à la question...

### Exercise 3

Boxplot:

```{r plastic-waste-boxplot}
ggplot(plastic_waste, aes(x=continent, y=plastic_waste_per_cap))+ geom_boxplot()
```

Violin plot:

```{r plastic-waste-violin}
ggplot(plastic_waste, aes(x=continent, y=plastic_waste_per_cap))+ geom_violin()
```

Réponse à la question...

### Exercise 4


```{r plastic-waste-mismanaged}
library(ggplot2)
ggplot(plastic_waste, aes(x=plastic_waste_per_cap, y=mismanaged_plastic_waste_per_cap, color=continent)) + geom_point()
```


### Exercise 5


```{r plastic-waste-population-total}
ggplot(plastic_waste, aes(x=plastic_waste_per_cap, y=total_pop))+ geom_point()


```

```{r plastic-waste-population-coastal}
ggplot(plastic_waste, aes(x=plastic_waste_per_cap, y=coastal_pop)) +geom_point()
```

Réponse à la question...

## Conclusion

Recréez la visualisation:

```{r recreate-viz}
library(dplyr)
plastic_waste_coastal <- plastic_waste  %>%
  mutate(coastal_pop_prop = coastal_pop / total_pop)  %>%
  filter(plastic_waste_per_cap < 3)

ggplot(plastic_waste_coastal, aes(x=coastal_pop_prop,  y=plastic_waste_per_cap, color=continent))+ 
geom_point() +  stat_smooth(aes(group = 1), color="BLACK")
labs(x= "Proportions de la population cotiere (Coastal/Total population)", y="Nombre de dechets de plastiques par habitant", title="Quantité de déchets plastiques vs Proportion de la population cotière",subtitle="Selon le continent")


```
